ktor:
  deployment:
    sslPort: 12388
  security:
    ssl:
      keyStore: build/keystore.jks
      keyAlias: sampleAlias
      keyStorePassword: foobar
      privateKeyPassword: foobar
  application:
    modules: [ br.nom.yt.re.ifciencia.localizadorwifi.MainKt.module ]
